start adding docker readme for auto-setup
temporalio/docker-builds pull request #224
Opened 2024-07-03 23:21 UTC by axfelix

@robholland how's this looking for a start? can push to dockerhub when complete

2024-07-05 12:23 UTC, robholland requested changes
Looking like a good place to start, a few comments.

2024-07-05 12:23 UTC, robholland commented on docker-readme/auto-setup.md
> +This variable specifies the type of database you're connecting to. Allowed values are `cassandra`, `mysql`, and `postgres`.
Valid values are: `cassandra`, `postgres12` and `mysql8`.

2024-07-05 12:23 UTC, robholland commented on docker-readme/auto-setup.md
> +`CASSANDRA_TLS_ENABLED` (defaults to unset)
would probably say "false" here for clarity although you are technically correct.

2024-07-05 12:23 UTC, robholland commented on docker-readme/auto-setup.md
> +`MYSQL_SEEDS` (defaults to unset)
This is the MySQL host name.

2024-07-05 12:23 UTC, robholland commented on docker-readme/auto-setup.md
> +`POSTGRES_SEEDS` (defaults to unset)
Postgresql host name.

2024-07-05 12:23 UTC, robholland commented on docker-readme/auto-setup.md
> +`ES_SEEDS` (defaults to unset)
Comma-separated list of Elasticsearch nodes.

2024-07-05 12:23 UTC, robholland commented on docker-readme/auto-setup.md
> +`ES_SCHEMA_SETUP_TIMEOUT_IN_SECONDS` (defaults to `0`)
0 meaning no timeout.

2024-07-05 12:23 UTC, robholland commented on docker-readme/auto-setup.md
> +`TEMPORAL_CLI_ADDRESS` (defaults to unset)
Let's just not mention this variable.

2024-07-08 13:06 UTC, robholland commented on docker-readme/auto-setup.md
> +This variable specifies whether Postgres should skip host key verification (e.g., in case your hostnames have changed recently and you need to work around a false positive red flag).
This is more generally used for server certificates which you can't easily verify, such as Amazon RDS.

2024-07-08 13:08 UTC, robholland approved these changes

2024-07-08 16:30 UTC, axfelix commented
@robholland looks like this still needs a review from @temporalio/server and then I'll push it up to dockerhub

2024-07-08 16:46 UTC, merged